# Homework Exercise 1

# 3

import sys
sys.path.append('/Users/giuliobene3000/Desktop/Programming/Python/Bioinformatics')

from DNA_toolkit import *
from strucs import *

my_sequence = 'CTACTGTAATTCAACACAACTGTTTAATAGTACTTGGTTTAATAG\
               TACTTGGAGTACTGAAGGGTCAAATAACACTGAAGGAAGTGACAC\
               AATCACCCTCCCATGCAGAATAAAACAAATTATAAACATGTGGCA\
               GAAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGTGGACAAAT\
               TAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGG\
               TGGTAATAGCAACAATGAGTCCGAGATCTTCAGACCTGGAGGAGG\
               AGATATGAGGGACAATTGGAGAAGTGAATTATATAAATATAAAGT\
               AGTAAAAATTGAACCATTAGGAGTAGCACCCACCAAGGCAAAGAG\
               AAGAGTGGTGCAGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTTT\
               GTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCAGC\
               CTCAATGACGCTGACGGTACAGGCCAGACAATTATTGTCTGGTAT\
               AGTGCAGCAGCAGAACAATTTGCTGAGGGCTATTGAGGCGCAACA\
               GCATCTGTTGCAACTCACAGTCTGGGGCAT'

my_rev_comp = reverse_complement(my_sequence)
print(my_rev_comp)

# print([codon_usage(my_sequence, amino)] for amino in Aminoacids)
